DROP TABLE IF EXISTS PROPOSALS;
CREATE TABLE PROPOSALS (
ID INTEGER NOT NULL,
LATITUDE DOUBLE,
LONGITUDE DOUBLE,
AFFINITY FLOAT,
LIST_INDEX INTEGER,
PRIMARY KEY (ID)
);
CREATE INDEX IX_LATITUDE ON PROPOSALS(LATITUDE);
CREATE INDEX IX_LONGITUDE ON PROPOSALS(LONGITUDE);
CREATE INDEX IX_AFFINITY ON PROPOSALS(AFFINITY);