ALTER TABLE LOCALES ADD COLUMN FAMA NUMERIC;
DROP TABLE IF EXISTS ACTIVIDADES;
CREATE TABLE ACTIVIDADES (
IDACTIVIDAD NUMERIC,
IDLOCAL NUMERIC,
NOMBRE TEXT,
DESCRIPCION TEXT,
INICIO DATETIME,
FIN DATETIME,
AFINIDAD NUMERIC,
IMAGENURL TEXT,
AFINIDADSTR TEXT,
FAMA NUMERIC,
TIPO NUMERIC,
PRIMARY KEY(IDACTIVIDAD, TIPO)
);
CREATE INDEX IX_AFINIDAD_ACTIVIDADES ON ACTIVIDADES(AFINIDAD ASC);
CREATE INDEX IX_FIN_ACTIVIDADES ON ACTIVIDADES(FIN ASC);
CREATE INDEX IX_TIPO_ACTIVIDADES ON ACTIVIDADES(TIPO ASC);
CREATE INDEX IX_ID_ACTIVIDADES ON ACTIVIDADES(IDACTIVIDAD ASC);
CREATE INDEX IX_ID_TIPO_ACTIVIDADES ON ACTIVIDADES(IDACTIVIDAD, TIPO);